### ISSUE TITLE
The 'Pods-DontStaticlib' target has transitive dependencies that include static binaries:...

### ISSUE THREAD

**Issue by dsencheng** [netease-im/NIM_iOS_UIKit#102] opened 2017-12-22 08:46 UTC
pod install 出现如下问题：

[!] The 'Pods-DontStaticlib' target has transitive dependencies that include static binaries: (/Users/dsen/Git/DClibrary/DontStaticlib/Pods/NIMSDK/NIMAVChat/Libs/libGPUImage.a, /Users/dsen/Git/DClibrary/DontStaticlib/Pods/NIMSDK/NIMAVChat/Libs/libnio.a, /Users/dsen/Git/DClibrary/DontStaticlib/Pods/NIMSDK/NIMAVChat/Libs/libNMCVideoModule.a, /Users/dsen/Git/DClibrary/DontStaticlib/Pods/NIMSDK/NIMAVChat/Libs/libnts.a, /Users/dsen/Git/DClibrary/DontStaticlib/Pods/NIMSDK/NIMAVChat/Libs/libnvs.a, /Users/dsen/Git/DClibrary/DontStaticlib/Pods/NIMSDK/NIMAVChat/Libs/libopenh264.a, /Users/dsen/Git/DClibrary/DontStaticlib/Pods/NIMSDK/NIMAVChat/Libs/libopus.a, /Users/dsen/Git/DClibrary/DontStaticlib/Pods/NIMSDK/NIMSDK/Libs/libaacplus.a, /Users/dsen/Git/DClibrary/DontStaticlib/Pods/NIMSDK/NIMSDK/Libs/libcrypto.a, /Users/dsen/Git/DClibrary/DontStaticlib/Pods/NIMSDK/NIMSDK/Libs/libevent.a, /Users/dsen/Git/DClibrary/DontStaticlib/Pods/NIMSDK/NIMSDK/Libs/libssl.a, /Users/dsen/Git/DClibrary/DontStaticlib/Pods/NIMSDK/NIMSDK/NIMSDK.framework, and /Users/dsen/Git/DClibrary/DontStaticlib/Pods/NIMSDK/NIMAVChat/NIMAVChat.framework)

Podfile 文件内容
platform :ios, '8.0'
use_frameworks!

target 'DontStaticlib' do
    pod 'NIMKit/Full'
end

cocoapods 版本:1.3.1

**Comment by chrisray108** [comment] 2017-12-25 09:40
Duplicate of #10

**Closed** 2017-12-25 09:40 UTC
